var api = {
    index: {
        banner: '/index/HomeImg',
        dynamic: '/index/topDynamic',
        login: '/user/getUserInfo',
        suggest: '/personal/Feedback',
        repairList: '/personal/warrantyList',
        repairType: '/personal/warranty_type',
        applyRepair: '/personal/warranty_claim',
        cancelRepair: '/personal/cancelApply',
        roomList: '/arrange/roomList',
        roomDetail: '/arrange/roomDetail',
        teaAppointment: '/arrange/teaRoom',
        roomAppointment: '/arrange/Reserve',
        createOrder: '/arrange/create_room_order',
        rommPay: '/arrange/pay',
		guide: '/index/help',
		activityList: '/index/active_list',
		activityDetail: '/index/active_detail',
		getBuilding: '/index/getBuilding',
		insertVisit: '/Index/insertVisit',
		cancelVisit: '/index/cancelVisit',
		getVisit: '/index/getVisit',
		is_yuyue: '/index/is_yuyue',
		getTimePeriod: '/arrange/getTimePeriod',
		getOpenRoomTimePeriod: '/arrange/getOpenRoomTimePeriod',
		getPhone: '/user/getMobile',
		complaintList: '/personal/FeedbackList',
    },
    discover: {
        company: '/arrange/aboutMiRui',
        banner: '/arrange/getFindImg',
        memberCompany: '/arrange/memberCompany',
        serviceList: '/arrange/businessList',
        serviceDetail: '/arrange/businessDetail'
    },
    trends: {
        list: '/Community/dynamicList',
        release: '/Community/newlyAdded',
        dolike: '/Community/insertFavor',
        reply: '/Community/insertComment',
        del: '/personal/deleteMyPublish'
    },
    message: {
        personList: '/Personal/myPersonalMsg',
        systemList: '/personal/mySystemMsg',
		getUnread: '/personal/getUnread',
    },
	center: {
		couponList: '/personal/myCoupon',
		riceBeans: '/mibean/miDouDetails',
		myAppointmentList: '/personal/mySubscribe',
		appointmentDel: '/personal/cancel',
		myBusinessList: '/personal/myCompany',
		myBusiness: '/personal/UserCompany',
		searchBusiness: '/personal/searchCompany',
		createEnterprise: '/personal/createCompany',
		joinEnterprise: '/personal/joinCompany',
		editEnterprise: '/personal/editCompany',
		quitEnterprise: '/personal/quitCompany',
		delEnterprise: '/personal/deleteCompany',
		waitStaff: '/personal/waitUserList',
		myStaff: '/personal/myStaff',
		delStaff: '/personal/deleteStaff',
		refuseStaff: '/personal/refuseJoinCompany',
		adoptStaff: '/personal/agreeJoinCompany',
        contract: '/personal/myContract',
        allBills: '/mybill/allBills',
        pendingPay: '/mybill/waitPayment',
        paid: '/mybill/AlreadyPayment',
		getCode: '/user/getCode',
		bindTel: '/user/bindUserTel',
		verifyTel: '/user/verifyPhone',
		editTel: '/user/changeBindMobile',
        bills: '/mybill/getMyAllBills',
        myPublish: '/personal/myPublish',
        billdetail: '/mybill/paymentdetail',
        useCoupons: '/mybill/clipCoupons',
        billWxPay: '/mybill/wxPay',
        billPublicPay: '/mybill/TransferPayment',
		poster:'/index/getPoster',
		reserve: '/arrange/myYuding',
		getUserInfo: '/user/getUserData',
		getPublicConfig: '/mybill/getPublicConfig',
	}
};

module.exports = api;
